default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crm_development
  # connection timeout
  timeout: 5000
  variables:
    statement_timeout: "20s"

test:
  <<: *default
  database: crm_test

production:
  <<: *default
  database: crm_production
  username: crm
  password: <%= ENV["CRM_DATABASE_PASSWORD"] %>
