default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crm_development

test:
  <<: *default
  database: crm_test

production:
  <<: *default
  database: crm_production
  username: crm
  password: <%= ENV["CRM_DATABASE_PASSWORD"] %>
